In [3]:
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd #for csv
import scipy.io as sio
import math

from sklearn.linear_model import LogisticRegression

# load the information in the file in a format that python can interpret
matTrainData = sio.loadmat("train.mat")
matTestData = sio.loadmat("test.mat")
#print(matData)
#matData.items() # 得知有哪些 items

#如何 element wise concate
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html
trainDataX = np.concatenate((np.array(matTrainData["x1"]), np.array(matTrainData["x2"])), axis=1 )
#print(trainDataX)
trainDataY = np.concatenate(np.array(matTrainData["y"])).astype(int)
print(trainDataY)

testX = np.concatenate((np.array(matTestData["x1"]), np.array(matTestData["x2"])), axis=1 )
testY = np.concatenate(np.array(matTestData["y"]))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [4]:
### Q1-5 ###
logreg = LogisticRegression(C=1e5, solver='lbfgs', multi_class='multinomial')

logreg.fit(trainDataX, trainDataY)
predictY = logreg.predict(testX)
#print(predictY)
#print(testY)
print(logreg.intercept_)
print(logreg.coef_)
count = 0
for i in range(len(predictY)):
    if predictY[i] != testY[i]:
        count +=1
print("percentage of misclassified test samples: %d %%" % (count/len(predictY)*100))

[37.85898317]
[[-18.34633961  19.23702253]]
percentage of misclassified test samples: 3 %


In [37]:
### Q1-6 ###
#P(C|x) -> P(C^x)/P(x) = h(W) = 1/(1 + e**(-W0 -W1*x1 - W2*x2) )
##[-36.03185422  45.27976297  51.53652281]
#initial values
W0 = 51.536
W1 = -36.0
W2 = 45.279
lr = 1000000
iteration = 100000 * 5

W0Lr = 0.0
W1Lr = 0.0
W2Lr = 0.0

W0_history = [W0]
W1_history = [W1]
W2_history = [W2]    

#print(len(trainDataX)) #70

#print(trainDataX)
def logistic_func(s):
    return 1/(1+np.exp(-s))
def predict_logistic(weight , x):
    x = np.append(x,one)
    score = logistic_func(np.dot(weight,x))
    if score > 0.5:
        return 1
    else:
        return 0
#y = trainDataY[0]
#x = trainDataX[n,:]
#print(weight*y)
#print( logistic_func(-y*(np.dot(weight,x)  )*(-y*x) ) )

#fuick
weight = np.random.uniform(size=[3])
print(weight)
weight = np.array([W1, W2, W0])
one = np.array([1])

for i in range(iteration):
    W0Grad = 0.0
    W1Grad = 0.0
    W2Grad = 0.0
    
    if i % 1000 == 0:
        acc = 0
        for n in range(len(testX)):
            x = testX[n,:]
            y = testY[n]
            pred = predict_logistic(weight,x)
            if pred == y:
                acc+=1
        print(acc/len(testX))
            
            
        print(weight)
        #print(W0, W1, W2)
#        print(W0Lr, W1Lr, W2Lr)
    
    #計算 gradient
    grad = np.zeros([3])
    for n in range(len( trainDataX)):
        x = trainDataX[n,:]
        y = trainDataY[n]
        if y == 0:
            y = -1
        x = np.append(x,one)
        grad += logistic_func(-y*(np.dot(weight,x)  ))*(-y*x) 
    #print(grad)
    
    grad /= len(trainDataX)
    weight -= grad 
    #break
    
    
    
    
    #W0Lr += W0Grad ** 2
    #W1Lr += W1Grad ** 2
    #W2Lr += W2Grad ** 2
    
    #更新 gradient
    #W0 = W0 - lr * W0Grad
    #W1 = W1 - lr * W1Grad
    #W2 = W2 - lr * W2Grad
    
    # Store parameters for plotting
    #W0_history.append(W0)
    #W1_history.append(W1)
    #W2_history.append(W2)
    


[0.5466269  0.65409235 0.85747976]
0.9666666666666667
[-36.     45.279  51.536]
0.9666666666666667
[-36.01406387  45.27354964  51.53411895]
0.9666666666666667
[-36.02091204  45.27225409  51.53361879]
0.9666666666666667
[-36.02461411  45.27277311  51.53372165]
0.9666666666666667
[-36.02693464  45.27408922  51.53408938]
0.9666666666666667
[-36.02864702  45.27575595  51.53457365]
0.9666666666666667
[-36.03009134  45.27757685  51.53510918]
0.9666666666666667
[-36.03141734  45.27946541  51.53566723]
0.9666666666666667
[-36.032691    45.28138351  51.53623513]
0.9666666666666667
[-36.0339414   45.28331435  51.53680729]
0.9666666666666667
[-36.03518136  45.28525051  51.53738127]
0.9666666666666667
[-36.03641654  45.28718874  51.53795597]
0.9666666666666667
[-36.03764942  45.28912759  51.53853091]
0.9666666666666667
[-36.0388811   45.29106643  51.53910588]
0.9666666666666667
[-36.04011208  45.29300498  51.5396808 ]
0.9666666666666667
[-36.04134257  45.2949431   51.54025561]
0.9666666666666667
[

0.9666666666666667
[-36.1890707   45.5276269   51.60939799]
0.9666666666666667
[-36.19026255  45.52950387  51.6099568 ]
0.9666666666666667
[-36.19145408  45.53138035  51.61051547]
0.9666666666666667
[-36.19264532  45.53325635  51.61107402]
0.9666666666666667
[-36.19383625  45.53513187  51.61163244]
0.9666666666666667
[-36.19502689  45.53700691  51.61219074]
0.9666666666666667
[-36.19621721  45.53888146  51.61274891]
0.9666666666666667
[-36.19740724  45.54075554  51.61330695]
0.9666666666666667
[-36.19859696  45.54262914  51.61386487]
0.9666666666666667
[-36.19978639  45.54450226  51.61442266]
0.9666666666666667
[-36.20097551  45.5463749   51.61498032]
0.9666666666666667
[-36.20216433  45.54824705  51.61553786]
0.9666666666666667
[-36.20335285  45.55011873  51.61609527]
0.9666666666666667
[-36.20454106  45.55198994  51.61665256]
0.9666666666666667
[-36.20572898  45.55386066  51.61720972]
0.9666666666666667
[-36.20691659  45.5557309   51.61776675]
0.9666666666666667
[-36.20810391  45.557

0.9666666666666667
[-36.34959555  45.78038795  51.68479837]
0.9666666666666667
[-36.35074732  45.78220121  51.68534036]
0.9666666666666667
[-36.3518988   45.78401403  51.68588222]
0.9666666666666667
[-36.35305     45.7858264   51.68642397]
0.9666666666666667
[-36.35420091  45.78763833  51.6869656 ]
0.9666666666666667
[-36.35535155  45.7894498   51.68750711]
0.9666666666666667
[-36.3565019   45.79126083  51.68804851]
0.9666666666666667
[-36.35765198  45.7930714   51.68858978]
0.9666666666666667
[-36.35880177  45.79488154  51.68913094]
0.9666666666666667
[-36.35995128  45.79669122  51.68967197]
0.9666666666666667
[-36.3611005   45.79850046  51.69021289]
0.9666666666666667
[-36.36224945  45.80030925  51.69075369]
0.9666666666666667
[-36.36339812  45.8021176   51.69129437]
0.9666666666666667
[-36.3645465   45.80392549  51.69183494]
0.9666666666666667
[-36.36569461  45.80573295  51.69237538]
0.9666666666666667
[-36.36684243  45.80753995  51.69291571]
0.9666666666666667
[-36.36798997  45.809

0.9666666666666667
[-36.50481498  46.02471942  51.75796454]
0.9666666666666667
[-36.50592935  46.02647328  51.75849072]
0.9666666666666667
[-36.50704345  46.02822672  51.75901679]
0.9666666666666667
[-36.50815728  46.02997974  51.75954274]
0.9666666666666667
[-36.50927085  46.03173234  51.76006858]
0.9666666666666667
[-36.51038416  46.03348453  51.76059431]
0.9666666666666667
[-36.51149721  46.03523629  51.76111993]
0.9666666666666667
[-36.51260999  46.03698764  51.76164543]
0.9666666666666667
[-36.51372251  46.03873857  51.76217083]
0.9666666666666667
[-36.51483476  46.04048909  51.76269611]
0.9666666666666667
[-36.51594676  46.04223918  51.76322128]
0.9666666666666667
[-36.51705849  46.04398886  51.76374634]
0.9666666666666667
[-36.51816996  46.04573812  51.76427129]
0.9666666666666667
[-36.51928116  46.04748697  51.76479613]
0.9666666666666667
[-36.5203921   46.0492354   51.76532085]
0.9666666666666667
[-36.52150279  46.05098341  51.76584547]
0.9666666666666667
[-36.5226132   46.052

In [27]:
print(weight)
print(logistic_func(-y*(np.dot(weight,x)  )*(-y*x) ))


[-27.32790701  33.19429454  42.61100013]
[2.45667815e-13 9.87729173e-08 4.60125600e-03]


In [7]:
#plt.plot([-188.4], [2.67], 'x', ms=12, markeredgewidth=3, color='orange')
plt.plot(θ1_history, θ2_history, 'o-', ms=3, lw=1.5, color='black')
plt.xlim(-25,-15)
plt.ylim(15,25)
plt.xlabel(r'$θ1$', fontsize=16)
plt.ylabel(r'$θ2$', fontsize=16)
plt.show()

print([θ0, θ1, θ2])

NameError: name 'θ1_history' is not defined